import "./globals.css";
import Header from "@/Components/Header";
import Navbar from "@/Components/Navbar";
import Providers from "./Providers";


export const metadata = {
  title: "SMT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
